// <auto-generated />
using System;
using HowToMakeCodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HowToMakeCodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260426231518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MusteriKayıtTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTcNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Oda", b =>
                {
                    b.Property<int>("OdaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdaId"));

                    b.Property<bool>("OdaDurum")
                        .HasColumnType("bit");

                    b.Property<int>("OdaFiyat")
                        .HasColumnType("int");

                    b.Property<int>("OdaKapasite")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdaOtel_Id")
                        .HasColumnType("int");

                    b.Property<int>("OtelId")
                        .HasColumnType("int");

                    b.HasKey("OdaId");

                    b.HasIndex("OtelId");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<int>("OdemeRezervasyon_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OdemeTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RezervasyonId")
                        .HasColumnType("int");

                    b.HasKey("OdemeId");

                    b.HasIndex("RezervasyonId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Otel", b =>
                {
                    b.Property<int>("OtelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtelId"));

                    b.Property<string>("OtelAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelSehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtelYıldızSayısı")
                        .HasColumnType("int");

                    b.HasKey("OtelId");

                    b.ToTable("Oteller");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonId"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.Property<int>("RezervastonOda_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervasyonCikis")
                        .HasColumnType("datetime2");

                    b.Property<string>("RezervasyonDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RezervasyonGiris")
                        .HasColumnType("datetime2");

                    b.Property<int>("RezervasyonMusteri_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("RezervasyonTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RezervasyonId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OdaId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Oda", b =>
                {
                    b.HasOne("HowToMakeCodeFirst.Models.Otel", "Otel")
                        .WithMany("Odalar")
                        .HasForeignKey("OtelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otel");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Odeme", b =>
                {
                    b.HasOne("HowToMakeCodeFirst.Models.Rezervasyon", "Rezervasyon")
                        .WithMany("Odemeler")
                        .HasForeignKey("RezervasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Rezervasyon", b =>
                {
                    b.HasOne("HowToMakeCodeFirst.Models.Musteri", "Musteri")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowToMakeCodeFirst.Models.Oda", "Oda")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Musteri", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Oda", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Otel", b =>
                {
                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("HowToMakeCodeFirst.Models.Rezervasyon", b =>
                {
                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
